### ISSUE TITLE
Missing custom fields when creating a new element

### ISSUE THREAD

**Issue by ArroyaveInformatik** [CompuMasterGmbH/cammUtils-vTigerNetApi#10]
Customs fields can be accessed and listed from all elements, but by creating new elements like accounts or contacts, cant find the custom field to give a value.

Custom fields can be called and updated but not created.

Best Regards
Alvaro A.

**Comment by jochenwezel** [comment]
Have you got a code snippet which you use for e.g. update?

**Comment by ArroyaveInformatik** [comment]
This issue have only tested with your demo.

1. Create a Custom field for a Contact in your vTiger WEB
2. Open VTiger Manager Demo
3. Go to contacts list (Your newly created custom filed will be listed)
4. Go to New ( All available fileds will be listed without the custom fields)...

**Comment by jochenwezel** [comment]
>but by creating new elements like accounts or contacts, cant find the custom field to give a value.

What is the exact error message which you get?

A word on the background process: 

1. the VTigerNetApi converts the VTiger_Contact class into some JSON. 
2. After that, the JSON request is sent to the VTiger application server. 
3. The VTiger application server has got its logic in its PHP files. If it crashes / can't handle a situation, the request may fail and an error posted to the user

In case the API backend of the VTiger application struggles to create/ fill a (custom) field, it might be an API implementation error at VTiger itself. But to ensure this, the exact error message is required (so, coming to the very first question)

**Comment by jochenwezel** [comment]
The latest version of the VTigerNetApi v2017.08.08 provides a little more error output.
E.g.:
![image](https://user-images.githubusercontent.com/3033827/29081207-2f6f1f5c-7c62-11e7-9978-3b58d77589bb.png)

1. Please update your project with the latest library. 
2. Please also update the demo application from latest GitHub sources.

Please note: you can update the VTigerNetApi library via NuGet since today - please also see https://www.nuget.org/packages/VTigerNetApi/

Please note 2: to copy the error output into this ticket, you might want to use the tool built into MS Windows: "Snipping Tool"
![image](https://user-images.githubusercontent.com/3033827/29081460-ee579700-7c62-11e7-8c18-08fff9de2490.png)

**Comment by ArroyaveInformatik** [comment]
1- Add a new custom field in **vTiger/Organisation**s like:
![image](https://user-images.githubusercontent.com/30500376/29407572-1bf98dba-8345-11e7-848d-1601f503e7c4.png)
2- By selecting **accounts** in the **demo project** will show the newly created custom field and their contents:
![image](https://user-images.githubusercontent.com/30500376/29407305-48bdf79c-8344-11e7-9636-99ccecbcf6c2.png)
3- Select **new in accounts** in order to create a new account will not be able to display the created custom field to be filled out

Note: By selecting account update is the custom field availble and can be filled out
No error are displayed in this process

**Comment by jochenwezel** [comment]
Okay, I see, when using the demo app and after clicking the button "New" at this location, the column is not visible in the main area
![image](https://user-images.githubusercontent.com/3033827/29424508-55987cda-8380-11e7-9028-11b7382039e8.png)
![image](https://user-images.githubusercontent.com/3033827/29424546-7574f84e-8380-11e7-9dfe-ade2162a768d.png)

This behaviour is for the demo app - but independent from the vtiger API library.
The demo app is not intended for production use and is not considered stable / free from errors/bugs.

**Comment by ArroyaveInformatik** [comment]
Yes, i know it

That's why I contacted you. We need a function in which these custom fields are also available for new datasets.
So I asked you about your effort to develop this implementation

**Comment by jochenwezel** [comment]
To be fixed for 

- [x] Organisation
- [x] Contacts

**Comment by jochenwezel** [comment]
@ArroyaveInformatik Querying the full column list for a vtiger table via the vtiger webservice requires at least 1 record in the table. So, if you've got a very new vtiger instance which contains absolutely NO data, we can't load the list of available columns. But as soon as the first record has been created, we're able to recieve the column list.

Would it be okay for you with this limitation caused by the vtiger webservice?

**Comment by jochenwezel** [comment]
The lastest source code contains a new method which provides the table schema as reported by the VTiger server:
DataTable dt = api.NewElementFromRemoteServerScheme(remoteTable);

Adding a caching of the remote table schema would be great, but this would be a separate feature request.
