### ISSUE TITLE
Error creating comments using demo app

### ISSUE THREAD

**Issue by MCSmit27** [CompuMasterGmbH/cammUtils-vTigerNetApi#25]
Hi,
I'm testing the demo app against my vTiger v7.1.0 crm. I can log in and the reading functions all work. However, when I try to create a Comment on and Account, I keep on getting the below error:

Post Request:
uri: https://xxx/webservice.php?operation=create
params (Url Encoded): sessionName=1d24c60b614315367ac01&elementType=ModComments&element={\"commentcontent\":\"Test\",\"assigned_user_id\":\"19x56\",\"createdtime\":\"2021-09-16T12:06:14.623451+02:00\",\"modifiedtime\":\"2021-09-16T12:06:14.623451+02:00\",\"related_to\":\"11x4614\",\"creator\":\"19x56\",\"parent_comments\":null,\"id\":null,\"elementType\":24}
params (Clean): sessionName=1d24c60b614315367ac01&elementType=ModComments&element=%7b%22commentcontent%22%3a%22Test%22%2c%22assigned_user_id%22%3a%2219x56%22%2c%22createdtime%22%3a%222021-09-16T12%3a06%3a14.623451%2b02%3a00%22%2c%22modifiedtime%22%3a%222021-09-16T12%3a06%3a14.623451%2b02%3a00%22%2c%22related_to%22%3a%2211x4614%22%2c%22creator%22%3a%2219x56%22%2c%22parent_comments%22%3anull%2c%22id%22%3anull%2c%22elementType%22%3a24%7d

Response:
{\"success\":false,\"error\":{\"code\":\"DATABASE_QUERY_ERROR\",\"message\":\"Database error while performing requested operation\"}}

I've asked my db admin to check the db logs and there are no db errors getting logged. I've also asked the infrastructure guys to check our any logs for the crm instance, and so far they could not find any errors either.

Any help or advise will be much appreciated!

**Comment by jochenwezel** [comment]
The vtiger .NET library just calls the webservice.php, but the final SQL statement is created by webservice.php. You have to take a look into the generated SQL statement which is sent to the database engine. From the "DATABASE_QUERY_ERROR" in your response, I expect e.g. an SQL syntax error in the SQL statement.

Since the SQL statement is created on server in webservice.php, the vtiger .NET library hasn't got a chance to change that behaviour.

Maybe you can test and try a workaround to 1st create the object and 2nd to update this object with the desired comment?
